apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    homework: level-9
  name: storage-class
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate

