apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    homework: level-9
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30079
  selector:
    homework: level-9
