apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sts
  labels:
    homework: level-9
spec:
  selector:
    matchLabels:
      homework: level-9
  serviceName: redis-svc
  replicas: 5
  template:
    metadata:
      labels:
        homework: level-9
      name: redis-pod
    spec:
      containers:
      - name: redis-container
        image: redis
