apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-line-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: print-line
          image: quay.io/vungocdat/print-line
          ports:
            - containerPort: 3000
