apiVersion: v1
kind: Service
metadata:
  name: print-line-clusterip-service
  labels:
    component: printline
spec:
  type: ClusterIP
  ports:
    - targetPort: 8080
      port: 8080
  selector:
    component: printline
