apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-line-deployment
  labels:
    component: printline
spec:
  replicas: 1
  selector:
    matchLabels:
      component: printline
  template:
    metadata:
      name: printline
      labels:
        component: printline
    spec:
      containers:
        - name: print-line-container
          image: quay.io/vungocdat/print-line:v1.2
          ports:
            - containerPort: 80
