apiVersion: v1
kind: Service
metadata:
  name: print-line-service
  labels:
    component: printline
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30003
  selector:
    component: printline
