apiVersion: v1
kind: Service
metadata:
  name: print-line-clusterip-service
  labels:
    component: printline
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    component: printline
