apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-line-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      name: print-line
      labels:
        component: web
    spec:
      containers:
        - name: print-line-container
          image: quay.io/vungocdat/print-line:1.1
