apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: alice
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQlpEQ0J6Z0lCQURBbE1RNHdEQVlEVlFRRERBVmhiR2xqWlRFVE1CRUdBMVVFQ2d3S1pHVjJaV3h2Y0dWeQpjekNCbnpBTkJna3Foa2lHOXcwQkFRRUZBQU9CalFBd2dZa0NnWUVBNWdsNFBBaFBHOS9OY2U3MDdkNmwybkxHCk9YQlVpRVEremMyYVBoWnNKTjRvazdaM0prak1nc081UUFrbW13MGo0a256Tm5ldlhqTnNUKzk5UUQrZUlweXIKMGtqUFN2Qm1pV1ZsMWpsOTFKb1lKTmI0VXU0SkhDUmk5cXg0d3N3ckM3b01ONTQ0UFo0ZHN6U2VZa01NakRTUwpjWUNPLzhhdzkxamV6ZVpOVVJjQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQkN3VUFBNEdCQUxjQXh0dVNWdFJqCndRSUdhSW91TGVFMmVGakdZLzl5YzR4SGRnMkFwVUtvK0xWSGFvMG5DeHlFeFRlbjhOaVpvNWc4TW1vSG9IYkcKWnFYeFFwU2RoM0ZPRkFwckRsMXpFOWJ2YUhWYmZkUUNYUno3eGZERXFoL0gyY2RwbFVvWXlwaWhaMHh4MFJrTApXcTk4bjZtbWtmc3pLRWRaMklQOUVWelppSFp0K0ZhYgotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
