apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob
spec:
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQllqQ0J6QUlCQURBak1Rd3dDZ1lEVlFRRERBTmliMkl4RXpBUkJnTlZCQW9NQ21SbGRtVnNiM0JsY25NdwpnWjh3RFFZSktvWklodmNOQVFFQkJRQURnWTBBTUlHSkFvR0JBTFY5eHo5U3FpZThjNXRiUGhmUG9NQTBVSld1Ci9nUGxwYWhCeEk5d2hzK2VFeVZ4NHpDUUlyM2ZnWldKd2x1UDZWT2dSNVBGaFU1T3hmOTgrcGFHVHp1OWlTckEKZDY0T2JOSCtLQ1h3WmVvQmxRa3BVOEQrKzYrdG8xREdrVFpvZ2Q1ZDdxWFhhMFErcHNMUEdkaW50MjN1NlU0QgpQWjFhM0hTK0oydkpLNi81QWdNQkFBR2dBREFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUUJWZGk2R1graUhtWGdiCkN0UFZwSzZPOWtiRUMzMFM3QXJJLzQxTVlIck1ZbmpQRG1OK0s0eFhFRjR6Wm5jL0IxMUkrQmJ3dEpFWFhWSzcKdUk2ZzQ3Z0FYeERCVUVieDhXNzFQNXh2NVk4K1IrLzFwSlZlQVhtY3BweVE4aVVhQ1Y3STUxWmxlMjJPSHBiZwo4TEFBZytyNzFESzlrRzBQSzR5ZFoxM25uNitRemc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
