apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-write-binding
  namespace: developers
roleRef:
  kind: Role
  name: read-write
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
